### ISSUE TITLE
Deployment issue: Linux Bastion Auto Scaling Group Failure: Command b-bootstrap failed 

### ISSUE THREAD

**Issue by KristyLapidus** [aws-quickstart/quickstart-amazon-redshift#36]
Hi,

Thanks for providing this CFN template for Redshift. I'm attempting to deploy it and cannot seem to get past an error with the embedded EC2 Linux Bastion stack deploying the Auto Scaling Group. The CFN event log error indicates: Unable to satisfy 100% MinSuccessfulInstancesPercent requirement for the ASG. 

Further details:

- I have not modified the template in any way
- I'm deploying into a new VPC
- I have reproduced the issue across multiple regions (US-east-1, US-west-2)
- The IAM user has the correct IAM permissions to create the resources required
- I've tried launching from both the Quickstart Guide and Github
- Limits/quotas should not be an issue because I'm not running anything else in this account. It is purely for testing purposes.
- I separately deployed the Linux Bastion Quickstart and it worked fine

The interesting thing is that the Auto Scaling Group does actually create successfully, as can be seen under the CloudFormation Stack / Resources tab. When I log into the EC2 instance to look at the log ( cat /var/log/cfn-* ), I see:

1. There is an error with Python 2.7 being deprecated
2. The Build fails with this message: 
[ERROR] Error encountered during build of config: Command b-bootstrap failed
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/cfnbootstrap/construction.py", line 542, in run_config
    CloudFormationCarpenter(config, self._auth_config).build(worklog)
  File "/usr/lib/python2.7/site-packages/cfnbootstrap/construction.py", line 260, in build
    changes['commands'] = CommandTool().apply(self._config.commands)
  File "/usr/lib/python2.7/site-packages/cfnbootstrap/command_tool.py", line 117, in apply
    raise ToolError(u"Command %s failed" % name)
ToolError: Command b-bootstrap failed
2020-11-30 22:28:40,124 [ERROR] -----------------------BUILD FAILED!------------------------
2020-11-30 22:28:40,130 [ERROR] Unhandled exception during build: Command b-bootstrap failed
Traceback (most recent call last):
  File "/usr/bin/cfn-init", line 171, in <module>
    worklog.build(metadata, configSets)
  File "/usr/lib/python2.7/site-packages/cfnbootstrap/construction.py", line 129, in build
    Contractor(metadata).build(configSets, self)
  File "/usr/lib/python2.7/site-packages/cfnbootstrap/construction.py", line 530, in build
    self.run_config(config, worklog)
  File "/usr/lib/python2.7/site-packages/cfnbootstrap/construction.py", line 542, in run_config
    CloudFormationCarpenter(config, self._auth_config).build(worklog)
  File "/usr/lib/python2.7/site-packages/cfnbootstrap/construction.py", line 260, in build
    changes['commands'] = CommandTool().apply(self._config.commands)
  File "/usr/lib/python2.7/site-packages/cfnbootstrap/command_tool.py", line 117, in apply
    raise ToolError(u"Command %s failed" % name)
ToolError: Command b-bootstrap failed

Let me know if you need more info.

Thanks!

**Comment by tonynv** [comment]
Stale, issue.
